apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oci-prd-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: oci-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./oci-prd-apps/
  prune: true
  validation: client
